import type { MetadataRoute } from 'next';
import { strings } from '@/lib/strings';
import { theme } from '@/config/theme';

/**
 * Web App Manifest (served at /manifest.webmanifest). Next.js auto-injects the
 * <link rel="manifest"> tag, so layout.tsx doesn't need to reference it.
 *
 * Colors are pulled from config/theme.ts so the install/splash chrome stays in
 * sync with the app. Icons are generated by scripts/generate-pwa-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: '/dashboard',
    name: strings.appName,
    short_name: strings.appName,
    description: strings.tagline,
    // Launch straight into the app home (avoids the '/' → '/dashboard' redirect flash on
    // cold start). Scope stays at '/' so every route is treated as in-app.
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    display_override: ['standalone', 'minimal-ui'],
    orientation: 'portrait',
    background_color: theme.colors.bg,
    theme_color: theme.colors.header,
    categories: ['travel', 'productivity', 'lifestyle'],
    icons: [
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/maskable-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icons/maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
